### ISSUE TITLE
Ajustar los textos a 80 caracteres

### ISSUE THREAD

**Issue by miguelinux** [gnuowned/iac-libro#24]
Mientras se hace la guia de estilo propuesta en https://github.com/gnuowned/iac-libro/issues/21, propongo **ajustar los textos a 80 caracteres** de ancho, esto con la finalidad de que sea mas fácil el manejo de los textos  y las revisiones de deferencias en  **git**.

**Comment by gnuowned** [comment]
Tocayo, 

 La propuesta es que "rompamos" las lineas despues de escribirlas?

Es decir:

1. escribimos todo el choro
2. rompemos las lineas con `make fold`
3. hacemos el commit

¿Entendí bien?

**Comment by miguelinux** [comment]
Tocayo,

Perdón por la demora,

Lo de **romper las lineas después** de escribirlas esa ya es tu decisión, como dueño del proyecto, 
por eso es importante la guia https://github.com/gnuowned/iac-libro/issues/21, y que digas si quieres
que sea hagan los textos a 80 caracteres o que los "**formateen**" después con el `make fold`.

El `make fold` tiene un **punto grabe**, ya que rompe lineas mayores de 80 caracteres que son URL o que son
salidas de consola. Tube que arreglar esos incovenientes en el PR https://github.com/gnuowned/iac-libro/pull/25, por eso digo que depende de la guia de estilos. 

Si usas 80 caracteres es mas fácil ver los cambios en el git pero también vienen inconvenientes como que
si te pasas tienes lineas de pocas palabras.

Tu tienes la última decisión
