### ISSUE TITLE
Agregar soporte para docker en el Makefile

### ISSUE THREAD

**Issue by galvarado** [gnuowned/iac-libro#27]
Me parece que vale la pena soportar docker ademas de podman, muchos siguen con docker todavia

**Comment by gnuowned** [comment]
Esto dices para que un contenedor genere las salidas?

**Comment by galvarado** [comment]
Si, ahora funciona con podman

make podman-html levanta un contianer para generar la salida, así no tienes dependencias de paquetes de ruby en tu sistema

Sugiero que también funcione con el cli de docker, no solo con el de podman.
