### ISSUE TITLE
Definir licencia y agregar al README

### ISSUE THREAD

**Issue by galvarado** [gnuowned/iac-libro#9]
Según la sugerencia inical de la Licencia (CC) me tomé la libertad de sugerir en el README la Licencia Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0) 

En esta Licencia eres libre de:

- Compartir: copia y redistribuye el material en cualquier medio o formato.

- Adaptarse: remezclar, transformar y construir sobre el material

El licenciante no puede revocar estas libertades siempre que siga los términos de la licencia. Bajo los siguientes términos:

- Atribución: se debe otorgar el crédito correspondiente, proporcionar un enlace a la licencia e indicar si se realizaron cambios. No se puede sugerir que el licenciante respalda los cambios o su uso.
-  Comercial: no se puede utilizar el material con fines comerciales.
- ShareAlike: si se remezcla, transforma o construye sobre el material, se deben distribuir las contribuciones bajo la misma licencia que el original.
- Sin restricciones adicionales: no se pueden aplicar términos legales o medidas tecnológicas que restrinjan legalmente a otros de hacer cualquier cosa que permita la licencia.

Detalles en:https://creativecommons.org/licenses/by-nc-sa/4.0/

**Comment by gnuowned** [comment]
Gracias, 

  Esa es la licencia que más me gustó a mi también, me prgunto si hay algún problema si luego la queremos cambiar. ¿Sabes?

**Comment by galvarado** [comment]
Ahora que estamos contribuyendo pocos creo que no hay problema, además no está liberado. Está publico pero es un trabajo todavia "entre amigos". Sin embargo mientras más pronto se pueda definir la licencia final, mejor.
